CC=gcc
CFLAGS=-I.
DEPS = FileSystemInfo.h fsLow.h

LIBS=-lm

%.o: %.c $(DEPS)
	$(CC) -c -o $@ $< $(CFLAGS)

fsDriver3: fsDriver3.o fsLow.o initializeFileSystem.o FileSystemControl.o driverFunctionP1.o driverFunctionP2.o driverFunctionP3.o driverFunctionP4.o checkFunctions.o checkFunctionsP1.o closeFileSystem.o
	$(CC) -o fsDriver3 fsLow.o fsDriver3.o initializeFileSystem.o FileSystemControl.o driverFunctionP1.o driverFunctionP2.o driverFunctionP3.o driverFunctionP4.o checkFunctions.o checkFunctionsP1.o closeFileSystem.o $(LIBS) 
